// GeneratePetInfo.js

// Get the pet's name from the URL
let pathArray = window.location.pathname.split('/');
let currentPetName = pathArray[pathArray.length - 1].replace('.html', '');

// Fetch the XML data
fetch('/src/xml/pets/pets.xml')
  .then(response => response.text())
  .then(data => {
    let parser = new DOMParser();
    let xmlDoc = parser.parseFromString(data, "text/xml");

    // Find the pet in the XML document
    let pets = xmlDoc.getElementsByTagName('pet');
    let currentPet;
    for(let pet of pets) {
      let lname = pet.getElementsByTagName('lname')[0].textContent;
      if(lname === currentPetName) {
        currentPet = pet;
        break;
      }
    }

    // Extract the pet's info
    let lname = currentPet.getElementsByTagName('lname')[0].textContent;
    let name = currentPet.getElementsByTagName('name')[0].textContent;
    let type = currentPet.getElementsByTagName('type')[0].textContent;
    let gender = currentPet.getElementsByTagName('gender')[0].textContent;
    let dob = currentPet.getElementsByTagName('dob')[0].textContent;
    let age = currentPet.getElementsByTagName('age')[0].textContent;
    let size = currentPet.getElementsByTagName('size')[0].textContent;
    let location = currentPet.getElementsByTagName('location')[0].textContent;
    let info = currentPet.getElementsByTagName('info')[0].textContent;

    // Generate the HTML
    let html = `
      <section id="adopt">
        <div class="adopt-pet">
          <div id="pet-gallery">
            <div class="big-image">
              <img id="big" src="/src/img/pets/${lname}1.png">
            </div>
            <div class="small-images">
              <img class="small active" src="/src/img/pets/${lname}1.png">
              <img class="small" src="/src/img/pets/${lname}2.png">
              <img class="small" src="/src/img/pets/${lname}3.png">
            </div>
          </div>
          <div class="adopt-info">
            <p>Hi! I am...</p>
            <hr>
            <h1>${name}</h1>
            <h2>${type} | ${gender}</h2>
            <hr>
            <h3>Location</h3>
            <p>${location}</p>
            <h3>Date of Birth</h3>
            <p>${dob}</p>
            <h3>Age</h3>
            <p>${age}</p>
            <h3>Size</h3>
            <p>${size}</p>
          </div>
        </div>
        <div class="adopt-story">
          <h1>My Story</h1>
          <p>${info}</p>
        </div>
      </section>
      <div class="ask-share">
        <div class="ask">
          <a href="/src/pages/nav/contact.html#form">
            <h1>Ask About <span>${name}</span></h1>
          </a>
        </div>
        <div class="share">
          <img src="/src/img/ui/share.png" alt="Share">
        </div>
      </div>
      <div class="pets-container">
          <!-- Generated by adoptOtherPets.js -->
      </div>
    `;

    // Get a reference to the main element
    let mainElement = document.querySelector('main');

    // Add the generated HTML to the main element
    mainElement.innerHTML += html;
  });
